spring:
  application:
    name: first-skin
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create


    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.sql: info
    org.hibernate.type: trace
  messages:
    basename: errors

pagination:
  size: 20
